name: main x86

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 체크아웃
        uses: actions/checkout@v2

      - name: 파이썬 3.8 환경 구축
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: 의존성 설치
        run: make install

      - name: 린터 실행
        run: make lint

      - name: 테스트 실행
        run: make test

      - name: 코드 포매팅
        run: make format

  build-container:
    runs-on: ubuntu-latest
    steps:

      - name: 체크아웃
        uses: actions/checkout@v2

      - name: 도커 허브 로그인
        uses: docker/login-action@v1
        with:
          username: protossdragoon
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 깃허브 컨테이너 레지스트리 로그인
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY }}

      - name: AWS 로그인
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: AWS ECR 로그인
        uses: aws-actions/amazon-ecr-login@v1

      - name: 컨테이너 빌드 후 도커 허브, 깃허브 레지스트리, AWS ECR에 동시에 푸시
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            protossdragoon/mlops-recipe_x86:v1
            ghcr.io/protossdragoon/mlops-recipe_x86:v1
            637917027048.dkr.ecr.us-east-1.amazonaws.com/mlops-recipe_x86:v1
